---
title: "CH_5_Modern-Dive"
author: "Matthew Garvin"
date: "10/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(moderndive)
library(skimr)
library(gapminder)
```

```{r}
evals_ch5 <- evals %>% 
  select(ID, score, bty_avg, age)
```

```{r}
glimpse(evals_ch5)
```

```{r}
evals_ch5 %>% 
  sample_n(size = 5)
```


```{r}
evals_ch5 %>% 
  summarise(mean_bty_avg = mean(bty_avg), mean_score = mean(score), median_bty_avg = median(bty_avg), median_score = median(score))
```


```{r}
evals_ch5 %>% 
  select(score, bty_avg) %>% 
  skim()
```



```{r}
evals_ch5 %>% 
  get_correlation(formula = score ~ bty_avg)
```

```{r}
evals_ch5 %>% 
  summarise(correlation = cor(score, bty_avg))
```


```{r}
ggplot(evals_ch5, aes(x=bty_avg, y=score)) +
  geom_point() +
  labs(x="Beauty Score", y="Teaching Score", title="Scatterplot of the relationship of teaching and beauty scores")
```

```{r}
ggplot(evals_ch5, aes(x=bty_avg, y=score)) +
  geom_jitter() +
  labs(x="Beauty Score", y="Teaching Score", title="Scatterplot of relationship of teaching and beauty scores") +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
evals_ch5 %>% 
  select(score, age) %>% 
  skim()
```


```{r}
evals_ch5 %>% 
  get_correlation(formula = score ~ age)
```


```{r}
ggplot(evals_ch5, aes(x=age, y=score)) +
  geom_jitter() +
  labs(x="Age", y="Teaching Score", title="Scatterplot of relationship of teaching scores and age") +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
score_model <- lm(score ~ bty_avg, data=evals_ch5)

get_regression_table(score_model)
```


```{r}
score_models <- lm(score ~ age, data=evals_ch5)

get_regression_table(score_models)
```



